export enum ApiURI {
  SIGN_IN = 'account/signin',
  SIGN_UP = 'account/signup',
  ME = 'account/me',
  CREDENTIAL_LIST = 'account/list',
  REFRESH_TOKEN = 'account/refresh',
  SHELVE_LIST = 'shelve/list',
  SHELVE_DETAIL= 'shelve/detail/',
  SHELVE_CREATE = 'shelve/create',
  SHELVE_UPDATE = 'shelve/update',
  SHELVE_DELETE = 'shelve/delete/',
  STOCK_LIST = 'stock/list',
  STOCK_DETAIL= 'stock/detail/',
  STOCK_CREATE = 'stock/create',
  STOCK_UPDATE = 'stock/update',
  STOCK_DELETE = 'stock/delete/',
  PRODUCT_LIST = 'product/list',
  PRODUCT_DETAIL = 'product/detail/',
  PRODUCT_CREATE = 'product/create',
  PRODUCT_UPDATE = 'product/update',
}
